# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uG4Ww5srUTOcajpRcs8Ob7BlOqLCkMLN
"""

list(range(2,10,2))