# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p3pj3uqaXg06fRoMQeokLMGnVx9Kz0Y5
"""

a=int(input('enter the number:'))
for i in range(1,11):
    print(a,'*',i,'=',a*i)